### ISSUE TITLE
VoiceSky- Self Care Portal 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#10]

**Comment by ZarshaB** [comment]
1>> Password should be standard with minimum 8 characters and having special character.
![image](https://user-images.githubusercontent.com/35685146/52939863-004a9480-3387-11e9-9a68-75041bb398e7.png)

**Comment by ZarshaB** [comment]
2>> Continue button should be disabled until user enters code.
![image](https://user-images.githubusercontent.com/35685146/52939983-4273d600-3387-11e9-9777-890982a69f9d.png)

**Comment by ZarshaB** [comment]
3>> There should be by default timer for all clients on "Resend Code" and "Call Me Again"buttons. 
User should wait during that time before pressing Resend or Call me again button. Button should be disabled until that time.
![image](https://user-images.githubusercontent.com/35685146/52940120-98487e00-3387-11e9-8c68-e964609a5ecd.png)

**Comment by ZarshaB** [comment]
4>> There should be space between Thank You of this page and also "Thank you for Register" success message appears after code entering.
![image](https://user-images.githubusercontent.com/35685146/52940212-ccbc3a00-3387-11e9-9c12-6b2b1124f9c3.png)

**Comment by ZarshaB** [comment]
5>> It should be "Your" instead of "You.
![image](https://user-images.githubusercontent.com/35685146/52940361-2de40d80-3388-11e9-8abb-84e584644eea.png)

**Comment by ZarshaB** [comment]
6>> It should display 0 instead of "Balance".
![image](https://user-images.githubusercontent.com/35685146/52940416-55d37100-3388-11e9-8e0b-b8728cc6263c.png)

**Comment by ZarshaB** [comment]
7>> This link needs to be changed on live site.
![image](https://user-images.githubusercontent.com/35685146/52940483-80252e80-3388-11e9-97f0-02c8051bdf54.png)

**Comment by ZarshaB** [comment]
8>> There should be payment Cancel/Success page.
![image](https://user-images.githubusercontent.com/35685146/52940589-bc588f00-3388-11e9-8ceb-3d4bcaaee59d.png)

**Comment by ZarshaB** [comment]
9>> Please create Send box test Account for testing.

**Comment by ZarshaB** [comment]
10>> If Account is in pending state then no services would be accessible by user no matter if he has created forwarding domains.

**Comment by ZarshaB** [comment]
11>> Top Up authentication.

**Comment by ZarshaB** [comment]
12>> I think both of these should be similar headings.
![image](https://user-images.githubusercontent.com/35685146/52940838-499be380-3389-11e9-9c4b-65f701d60322.png)

**Comment by ZarshaB** [comment]
13>> There should be blockUI for city as it opens multiple pop ups.
![image](https://user-images.githubusercontent.com/35685146/52940956-92539c80-3389-11e9-9493-460ee83f5a23.png)

**Comment by ZarshaB** [comment]
14>> One city name should be changed to City Code.
![image](https://user-images.githubusercontent.com/35685146/52940995-ab5c4d80-3389-11e9-8041-7e05b75f7f85.png)

**Comment by ZarshaB** [comment]
15>> There should be cross icon.
![image](https://user-images.githubusercontent.com/35685146/52941069-ca5adf80-3389-11e9-9623-92d0e97c7749.png)

**Comment by ZarshaB** [comment]
16>> Cursor should be displayed for detail. It should show that this field is clickable.
![image](https://user-images.githubusercontent.com/35685146/52941104-dc3c8280-3389-11e9-9565-9e44cf9e9971.png)

**Comment by ZarshaB** [comment]
16>> It requires customization. Only show fields that are require.
![image](https://user-images.githubusercontent.com/35685146/52941228-1d349700-338a-11e9-83ad-d7dc1030878d.png)

**Comment by ZarshaB** [comment]
17>> It is displaying broken image and name.
![image](https://user-images.githubusercontent.com/35685146/52941283-39d0cf00-338a-11e9-8622-5c57eebb2913.png)

**Comment by ZarshaB** [comment]
18>> Please make it "fields".
![image](https://user-images.githubusercontent.com/35685146/52941345-5ec54200-338a-11e9-9e98-a7ce0261326f.png)

**Comment by ZarshaB** [comment]
19>> On removing forwarding it should display remove forwarding success message.
![image](https://user-images.githubusercontent.com/35685146/52941456-a77cfb00-338a-11e9-9387-c58f97ad7631.png)

**Comment by ZarshaB** [comment]
20>> Each activity logs should be there.

**Comment by ZarshaB** [comment]
21>> Menus should expand to show current page.
![image](https://user-images.githubusercontent.com/35685146/52941599-0478b100-338b-11e9-8738-664fa3d7f57c.png)

**Comment by ZarshaB** [comment]
22>> Borders should be outside all text boxes.

**Comment by ZarshaB** [comment]
23>> It would be better if we display all messages on required fields instead of displaying at top. And heading would be fixed at point instead of moving downwards.
![image](https://user-images.githubusercontent.com/35685146/52942269-7dc4d380-338c-11e9-8caf-5adca5bab743.png)

**Comment by ZarshaB** [comment]
24>> Please change it to "process". Change this message to this:
"Call is in process and Account Key will be there. Enter that account key to verify your phone. 
![image](https://user-images.githubusercontent.com/35685146/52946723-90440a80-3396-11e9-9b27-2a0b76298f0f.png)

**Comment by ZarshaB** [comment]
**Re-opened**
5>> The success message it displays is for very less time that I can't even read it. And also if I update anything else then it removes me profile picture.
![image](https://user-images.githubusercontent.com/35685146/53006552-3bb49400-3457-11e9-9fd1-a68ec59c14ab.png)

**Comment by ZarshaB** [comment]
**Re-opened** 
It is still there, 
15>> Cursor should be displayed for detail. It should show that this field is clickable.
![image](https://user-images.githubusercontent.com/35685146/52941104-dc3c8280-3389-11e9-9565-9e44cf9e9971.png)

**Comment by ZarshaB** [comment]
25>> Pop up open with a jerk. It should be smooth.
![image](https://user-images.githubusercontent.com/35685146/53007309-cd70d100-3458-11e9-9202-0781d4ab28b9.png)

**Comment by ZarshaB** [comment]
26>> As on clicking on sign up I'm redirecting to error page so not able to test sign up page issues. (1,2,24)
![image](https://user-images.githubusercontent.com/35685146/53008294-e1b5cd80-345a-11e9-9126-a49617772509.png)

**Comment by ZarshaB** [comment]
1>> It should display this message.
Your password must be at least 8 characters long, contain at least one number and have a mixture of uppercase and lowercase letters.

**Comment by ZarshaB** [comment]
27>> Please only enter letters, numbers and underscores. 
![image](https://user-images.githubusercontent.com/35685146/53024703-5dc30c00-3481-11e9-989d-5fc8194d8900.png)

**Comment by ZarshaB** [comment]
28>> Please add that at highlighted area and remove comma as ".... that you are the owner...."
![image](https://user-images.githubusercontent.com/35685146/53074765-63feca00-350d-11e9-91f4-2eaee3bdd55c.png)

**Comment by ZarshaB** [comment]
29>> Please make it "Successful Transaction" or "Transaction is successful."
![image](https://user-images.githubusercontent.com/35685146/53077187-4cc2db00-3513-11e9-96f7-7df94e96de78.png)

**Comment by ZarshaB** [comment]
30>> Please change it to "within" instead of "with in".
![image](https://user-images.githubusercontent.com/35685146/53078921-138c6a00-3517-11e9-8101-220cf211f706.png)

**Comment by ZarshaB** [comment]
**Reopened**
Still there. 
 17>> It is displaying broken image and name.
![image](https://user-images.githubusercontent.com/35685146/52941283-39d0cf00-338a-11e9-8622-5c57eebb2913.png)

**Comment by ZarshaB** [comment]
**@Haider will tell how to test this.** 
10>> If Account is in pending state then no services would be accessible by user no matter if he has created forwarding domains.

**Comment by ZarshaB** [comment]
26>> Error message is not disappearing. 
And if I search for Brazil and then search for Canada then it still displays Brazil results.
![image](https://user-images.githubusercontent.com/35685146/53164247-997ce380-35f1-11e9-9084-e42df0f330de.png)

**Comment by ZarshaB** [comment]
27>> Please change this message to:
"Already have an account? Sign in"
![image](https://user-images.githubusercontent.com/35685146/53240287-242c1400-36c0-11e9-9ea9-f48249d5b6db.png)

**Comment by ZarshaB** [comment]
28>> Please change this message to:
"We thought so too but due to some mumbo-jumbo, you can Topup minimum of  $5.00."
![image](https://user-images.githubusercontent.com/35685146/53252307-61a09980-36e0-11e9-97f0-b088f1c1d4a1.png)

**Comment by ZarshaB** [comment]
**Re-opened**
8>> Please change this message to:
"Transaction Rolled Back successfully."
![image](https://user-images.githubusercontent.com/35685146/53252677-46825980-36e1-11e9-9569-c09ef5dd8f85.png)

**Comment by ZarshaB** [comment]
29>> Please change this message to:
"Oooopsss!!! Something went wrong. Please try later." 
![image](https://user-images.githubusercontent.com/35685146/53252780-834e5080-36e1-11e9-8c09-8173f45314e3.png)

**Comment by ZarshaB** [comment]
29>> Please change this message to:
"Oooopss!!!
We thought so too but due to some mumbo-jumbo, you can Topup minimum of $5.00."
![image](https://user-images.githubusercontent.com/35685146/53252915-d6280800-36e1-11e9-96b5-b57353816181.png)

**Comment by sammiullah** [comment]
**8 27 28 29**
**RFR**

**Comment by ZarshaB** [comment]
23>> Currency should be same throughout site.
![image](https://user-images.githubusercontent.com/35685146/53417940-763ea380-39f8-11e9-9bcb-f62995bcada6.png)

**Comment by ZarshaB** [comment]
23>> There will be Transaction instead of payment I think.
![image](https://user-images.githubusercontent.com/35685146/53497603-5ecdec00-3ac6-11e9-93c4-3a28cd185a1a.png)

**Comment by ZarshaB** [comment]
24>> Profile picture is not uploading on display.
![image](https://user-images.githubusercontent.com/35685146/53497826-e582c900-3ac6-11e9-9076-7b302a182b3e.png)

**Comment by ZarshaB** [comment]
25>> This icon does not move if I do not click on Search button. 
![image](https://user-images.githubusercontent.com/35685146/53498584-68585380-3ac8-11e9-94a5-d9ef5f55c822.png)

**Comment by ZarshaB** [comment]
26>> Search is not working because on clicking on Search it displays empty page.
![image](https://user-images.githubusercontent.com/35685146/53500430-1adde580-3acc-11e9-8988-ac11fd30a766.png)

**Comment by ZarshaB** [comment]
27>> It should display total Amount below the fields.
![image](https://user-images.githubusercontent.com/35685146/53500542-5aa4cd00-3acc-11e9-86d2-03d52d708ba4.png)

**Comment by ZarshaB** [comment]
25>> I bought two DIDs of Brazil having $43 and $23 respectively. I paid amount by using Wallet. In Top up I had $200. But after purchasing my balance became $540.
![image](https://user-images.githubusercontent.com/35685146/53501290-b1f76d00-3acd-11e9-99d7-626ef6511d3d.png)

**Comment by ZarshaB** [comment]
26>> There should also be dollar sign before balance and it should be two decimal places. 
![image](https://user-images.githubusercontent.com/35685146/53740889-09734f80-3eb7-11e9-8cb7-883fc6f73701.png)

**Comment by ZarshaB** [comment]
27>> Please change heading to "Change Password".
Also please apply same checks for password as we have on sign up page.
![image](https://user-images.githubusercontent.com/35685146/53796976-10519f00-3f57-11e9-8080-cbfeafb8719c.png)

**Comment by ZarshaB** [comment]
28>> This Call Me Again button should be "Call Me" at first and then after user has called once then it should change to "Call Me Again." and also it should not change as time increases.
