### ISSUE TITLE
Voicesky  - Admin Portal 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#11]

**Comment by ZarshaB** [comment]
1>> There should be voicesky logo in favicon.
![image](https://user-images.githubusercontent.com/35685146/52941751-61746700-338b-11e9-9768-5ee9bd219dcc.png)

**Comment by ZarshaB** [comment]
2>> It should display "Invalid username or password."
![image](https://user-images.githubusercontent.com/35685146/52941857-92549c00-338b-11e9-8d16-cea7b892419f.png)

**Comment by ZarshaB** [comment]
3>> Both buttons should be on one side. 
![image](https://user-images.githubusercontent.com/35685146/52942021-e52e5380-338b-11e9-806d-2f71b5526e96.png)

**Comment by ZarshaB** [comment]
4>> Please change "Active" button to "Approve".
![image](https://user-images.githubusercontent.com/35685146/52942054-fa0ae700-338b-11e9-8487-6927cf03fd2c.png)

**Comment by ZarshaB** [comment]
5>> Session should not time out while user is using site.
![image](https://user-images.githubusercontent.com/35685146/52942315-96cd8480-338c-11e9-894c-a576776a909a.png)

**Comment by ZarshaB** [comment]
6>> There should also be labels of "Parent Class of Service" and "Child Class of Service" for these two fields.
![image](https://user-images.githubusercontent.com/35685146/52942410-c7adb980-338c-11e9-882c-9be0eccee5e8.png)

**Comment by ZarshaB** [comment]
7>> There should be check that minimum top up should be 5. And it should not allow it to edit.
![image](https://user-images.githubusercontent.com/35685146/52942549-017ec000-338d-11e9-9598-881a84c9c526.png)

**Comment by ZarshaB** [comment]
8>> There should be label of "System Notification Email" and in bracket it should written:
( You can add as many comma separating emails as you want. )
![image](https://user-images.githubusercontent.com/35685146/52942675-3be85d00-338d-11e9-8769-93879989f109.png)

**Comment by ZarshaB** [comment]
9>> There should be Saller Name field too.
![image](https://user-images.githubusercontent.com/35685146/52942744-65a18400-338d-11e9-8796-b6ed7c5539a1.png)

**Comment by ZarshaB** [comment]
10>> There should be Active option.
![image](https://user-images.githubusercontent.com/35685146/52942796-836ee900-338d-11e9-98b0-3e8ba890c060.png)

**Comment by ZarshaB** [comment]
11>> Menus should expand to show current page.

**Comment by ZarshaB** [comment]
12>> There should be three categories pages of Pending, Approved , Rejected. And also buttons on each page similar to Reseller.
For Rejected page there should be Approve button.
![image](https://user-images.githubusercontent.com/35685146/52942968-e06a9f00-338d-11e9-836c-cb88e019541e.png)

**Comment by ZarshaB** [comment]
13>> Confirmation message of "Are you sure..." should display before each action.

**Comment by ZarshaB** [comment]
14>> Payment details could also be visible. There should be option for viewing detail of payment. And clicking on that it should redirect to detail page.
![image](https://user-images.githubusercontent.com/35685146/52943073-20ca1d00-338e-11e9-9b9a-397acd037b3d.png)

**Comment by ZarshaB** [comment]
15>> Time format should be same for whole site. All web servers should sync for time.

**Comment by ZarshaB** [comment]
16>> All web servers should sync for time.

**Comment by ZarshaB** [comment]
17>> There should be Change password option for Admin account.

**Comment by ZarshaB** [comment]
**Re-opened**
12>> Instead of Cancel it should be "Reject". 
In Approved category there should be two buttons of "Reject" and "Detail".
![image](https://user-images.githubusercontent.com/35685146/53078627-72051880-3516-11e9-833c-2f6db9a3ff28.png)

**Comment by ZarshaB** [comment]
18>> These pending payments should be in Pending Payments category.
![image](https://user-images.githubusercontent.com/35685146/53079129-96152980-3517-11e9-9edc-6ace6aa29bc5.png)

**Comment by ZarshaB** [comment]
7>> It has saved top up 2.00 and didn't showed me any error message.
And also from update system settings it is also saving top up less than 5 but after updating it again make it 5.00. 
![image](https://user-images.githubusercontent.com/35685146/53079398-218eba80-3518-11e9-9d0d-246f2f385918.png)

**Comment by ZarshaB** [comment]
18>> These pending payments of live Approve account should be in Pending Payments category.
![image](https://user-images.githubusercontent.com/35685146/53079909-46cff880-3519-11e9-98b6-18ffacc60123.png)

**Comment by ZarshaB** [comment]
18>> Complete Calendar is not appearing.
![image](https://user-images.githubusercontent.com/35685146/53349090-26030b00-393e-11e9-8a03-55f7c08915ab.png)

**Comment by ZarshaB** [comment]
17>> This icon does not move if I do not click on Search button. 
![image](https://user-images.githubusercontent.com/35685146/53498584-68585380-3ac8-11e9-94a5-d9ef5f55c822.png)

**Comment by ZarshaB** [comment]
18>> Search is not working because on clicking on Search it displays empty page.
![image](https://user-images.githubusercontent.com/35685146/53500430-1adde580-3acc-11e9-8988-ac11fd30a766.png)

**Comment by ZarshaB** [comment]
19>> It should display total Amount below the fields.
![image](https://user-images.githubusercontent.com/35685146/53500542-5aa4cd00-3acc-11e9-86d2-03d52d708ba4.png)

**Comment by ZarshaB** [comment]
20>> I bought DID for AlizayAli@gmail.com account. It was in pending state when I bought DID. But on Admin Portal it is not appearing in DID tab or even in Topup Tab. Even after I have approved the account.
![image](https://user-images.githubusercontent.com/35685146/53500804-d9016f00-3acc-11e9-8dcc-a6d6aff11fd5.png)

**Comment by asifjans** [comment]
21>> Create following API Functions for Reseller Portal

1) CDR Reports 
   -> Function name: **CDRReportsByDIDNumber**
   -> Type: GET
2) Topup History 
   -> Function name: **TopupHistory**
   -> Type: GET

**Comment by ZarshaB** [comment]
22>> Admin must be able to view list of api credentials with seller details
a) any time admin should have access to de-activate/activate API
b) also maintain log, who deactivated the api with reason.

**Comment by ZarshaB** [comment]
23>> When I click on checkbox and enter into field. Then I click on "Update" but no action performed. And when I refreshed the page then update field disappeared. 
![image](https://user-images.githubusercontent.com/35685146/53625352-ac606b00-3c24-11e9-9c6c-2682d6ea1818.png)

**Comment by ZarshaB** [comment]
24>> Badge does not disappears even after I have approved pending Payments. And also unread sign not disappears after I have opened that account.
![image](https://user-images.githubusercontent.com/35685146/53625500-1a0c9700-3c25-11e9-8475-2933c429a5f9.png)
![image](https://user-images.githubusercontent.com/35685146/53625517-22fd6880-3c25-11e9-9ae6-912bf51a8cb4.png)

**Comment by ZarshaB** [comment]
24>> For Empty page display this message:
Ooops!!!
This place looks like The Empty Quarter. Lets fill it up and buy some items.
![image](https://user-images.githubusercontent.com/35685146/53625779-d9614d80-3c25-11e9-8dfd-4635bd26447b.png)

**Comment by ZarshaB** [comment]
23>> Pop up is opening more than once if I click on update more than once.
![image](https://user-images.githubusercontent.com/35685146/53642564-e85ef480-3c53-11e9-8ec0-1655ca15d403.png)

**Comment by ZarshaB** [comment]
24>> When I approve account then Marginal Percentage, API access etc field does not appear automatically and I have to refresh my account. Also when I approve DID then that DID does not appear in DID tab. I have to again come to the page from Reseller page.

**Comment by ZarshaB** [comment]
18>> Search is not working for current day like if I select To and From date to same date then it does not show me any results.
![image](https://user-images.githubusercontent.com/35685146/53500430-1adde580-3acc-11e9-8988-ac11fd30a766.png)

**Comment by ZarshaB** [comment]
26 >> Adjust this table according to space.
![image](https://user-images.githubusercontent.com/35685146/53649456-fcaaed80-3c63-11e9-8e68-365cb5ec8638.png)

**Comment by ZarshaB** [comment]
27>> Please remove text after Login from Page title. 
![image](https://user-images.githubusercontent.com/35685146/53728979-c94fa500-3e95-11e9-843c-097a0488c322.png)

**Comment by ZarshaB** [comment]
22>> I need to test it with API.

**Comment by ZarshaB** [comment]
27>> It's pop up appears more than once. And also please display it's status value.
![image](https://user-images.githubusercontent.com/35685146/53741423-2bb99d00-3eb8-11e9-8ba2-73fa17e468f0.png)

**Comment by ZarshaB** [comment]
27>> In this it asks for reason while cancelling payment but it does not asks for reason for suspending an account. And also where these reasons will be displayed? 
>> Admin decline/ suspend order then display reason. For Approval of order it is optional to display reason

**Comment by ZarshaB** [comment]
28>> Please change it's currency sign to dollar.
![image](https://user-images.githubusercontent.com/35685146/53798355-ec438d00-3f59-11e9-8635-5c574f36d130.png)

**Comment by ZarshaB** [comment]
29>> If there is no entry in payment then no badge should appear there. 
![image](https://user-images.githubusercontent.com/35685146/53802672-3e89ab80-3f64-11e9-8eac-dad70c952bd5.png)
