### ISSUE TITLE
DID Pooling 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#13]

**Comment by asifjans** [comment]
**DID Pooling Flow:**

-> Reseller will get the dids based on its Marginal percentage.
-> There will be a reseller account that will be used for pooling. That account won't be able to login to reseller portal and will be managed through admin portal.(For purchasing DIDs).
-> Two tables will be created to manage the pooling. 
 1) DIDPoolingAccounts ( ResellerId, DIDOrderId, CreatedDate)
 2) DIDPoolingAccountHistory (PoolingAccountId, ResellerId, FromDateTime, ToDateTime, IsActive).
