### ISSUE TITLE
Reseller - Quick feedback

### ISSUE THREAD

**Issue by asifjans** [asifjans/voicesky#14]
3) i created an account
![image](https://user-images.githubusercontent.com/10880558/53801104-16984900-3f60-11e9-8c51-a34a69acec41.png)

B) on timer change. button was moving left right as i shared....

**Comment by asifjans** [comment]
4) on change password regular expression was not added
![image](https://user-images.githubusercontent.com/10880558/53801447-02a11700-3f61-11e9-8387-d7bd12b9f94a.png)

**Comment by asifjans** [comment]
5) validation message must be close to the textboxes instead of 
![image](https://user-images.githubusercontent.com/10880558/53801506-33814c00-3f61-11e9-8b7d-edf30e7ca307.png)

**Comment by asifjans** [comment]
6) i see pound in email
![image](https://user-images.githubusercontent.com/10880558/53802205-0df54200-3f63-11e9-9e93-288615c79cd1.png)

**Comment by asifjans** [comment]
7) payment emails
![image](https://user-images.githubusercontent.com/10880558/53802286-47c64880-3f63-11e9-8b57-d81f50bd24af.png)

**Comment by asifjans** [comment]
8) if i access this page left menu must be auto expand 
http://voicesky.net/Plans/BuySIPTrunkingPlan
![image](https://user-images.githubusercontent.com/10880558/53802487-c3c09080-3f63-11e9-8732-745f5b470e24.png)

**Comment by asifjans** [comment]
9)
a) if my account is approved i must get an email with information
b) if my payment is approved,  i must get an email with details.

**Comment by asifjans** [comment]
10) i was logged in, my account was still pending although it was approved by admin.

11) i logged out and re login then it was showing approved

**Comment by asifjans** [comment]
12) this is meaninguless 
![image](https://user-images.githubusercontent.com/10880558/53802930-fb7c0800-3f64-11e9-905f-2927b1ffafcd.png)

**Comment by asifjans** [comment]
13) i am logged my account status was changed, but i am still using....

**Comment by asifjans** [comment]
14) if status of acount is updated must get email.

**Comment by ZarshaB** [comment]
15>> If there is no entry in payment then no badge should appear there. 
![image](https://user-images.githubusercontent.com/35685146/53802672-3e89ab80-3f64-11e9-8eac-dad70c952bd5.png)

**Comment by ZarshaB** [comment]
16>> In this it asks for reason while cancelling payment but it does not asks for reason for suspending an account. And also where these reasons will be displayed? 
>> Admin decline/ suspend order then display reason. For Approval of order it is optional to display reason

**Comment by ZarshaB** [comment]
17 >> Adjust this table according to space.
![image](https://user-images.githubusercontent.com/35685146/53649456-fcaaed80-3c63-11e9-8e68-365cb5ec8638.png)

**Comment by ZarshaB** [comment]
18>> When I approve account then Marginal Percentage, API access etc field does not appear automatically and I have to refresh my account. Also when I approve DID then that DID does not appear in DID tab. I have to again come to the page from Reseller page.

**Comment by ZarshaB** [comment]
19 >> There should also be dollar sign before balance and it should be two decimal places. 
![image](https://user-images.githubusercontent.com/35685146/53740889-09734f80-3eb7-11e9-8cb7-883fc6f73701.png)

**Comment by ZarshaB** [comment]
20>> Please change heading to "Change Password".
Also please apply same checks for password as we have on sign up page.
![image](https://user-images.githubusercontent.com/35685146/53796976-10519f00-3f57-11e9-8080-cbfeafb8719c.png)

**Comment by ZarshaB** [comment]
21>> There will be four status:
Active, Waiting for Approval, Suspend, In Process.
User should be displayed with status of his account.

**Comment by ZarshaB** [comment]
22>> Original Price of DID should display to Admin. As for now it is showing price by adding marginal fee.

**Comment by ZarshaB** [comment]
23>> Please add space between Forgot and Password.
![image](https://user-images.githubusercontent.com/35685146/53804252-dbe6de80-3f68-11e9-859c-3b55eb483dfa.png)

**Comment by adeelilyas81** [comment]
> 1. Password must complete both Info_478 OR Info*478
Adeel: Must be fixed.

> 2. I see alert as i signup
> Adeel: Alert must be removed

> ![image](https://user-images.githubusercontent.com/10880558/53800648-0469db00-3f5f-11e9-8f65-3f696384771a.png)
> 
> 1. i created an account
>    ![image](https://user-images.githubusercontent.com/10880558/53801104-16984900-3f60-11e9-8c51-a34a69acec41.png)
> 
> i never called but i say text of button as "Call me again"
> 
> i click on "Call me again" after calling it was converted to "Call me" instead of it must be "Call me again"
> 
> on timer change. button was moving left right as i shared....

Must be fixed.

> 1. Password must complete both Info_478 OR Info*478
> 2. I see alert as i signup
> 
> ![image](https://user-images.githubusercontent.com/10880558/53800648-0469db00-3f5f-11e9-8f65-3f696384771a.png)
> 
> 1. i created an account
>    ![image](https://user-images.githubusercontent.com/10880558/53801104-16984900-3f60-11e9-8c51-a34a69acec41.png)
> 
> i never called but i say text of button as "Call me again"
> 
> i click on "Call me again" after calling it was converted to "Call me" instead of it must be "Call me again"
> 
> on timer change. button was moving left right as i shared....

**Comment by adeelilyas81** [comment]
> 1. Password must complete both Info_478 OR Info*478
**Adeel** Must be Fixed
> 2. I see alert as i signup
> **Adeel** Must be fixed
> ![image](https://user-images.githubusercontent.com/10880558/53800648-0469db00-3f5f-11e9-8f65-3f696384771a.png)
> 
> 1. i created an account
>    ![image](https://user-images.githubusercontent.com/10880558/53801104-16984900-3f60-11e9-8c51-a34a69acec41.png)
> 
> i never called but i say text of button as "Call me again"
> 
> i click on "Call me again" after calling it was converted to "Call me" instead of it must be "Call me again"
> 
> on timer change. button was moving left right as i shared....
**Adeel** Must be fixed

**Comment by adeelilyas81** [comment]
> 1. on change password regular expression was not added
>    ![image](https://user-images.githubusercontent.com/10880558/53801447-02a11700-3f61-11e9-8387-d7bd12b9f94a.png)

**Adeel** Must be fixed

**Comment by sammiullah** [comment]
FIXED 23>> Please add space between Forgot and Password.
![image](https://user-images.githubusercontent.com/35685146/53804252-dbe6de80-3f68-11e9-859c-3b55eb483dfa.png)

**Comment by sammiullah** [comment]
FIXED 22>> Original Price of DID should display to Admin. As for now it is showing price by adding marginal fee

**Comment by sammiullah** [comment]
**FIXED** 20>> Please change heading to "Change Password".
Also please apply same checks for password as we have on sign up page.
![image](https://user-images.githubusercontent.com/35685146/53796976-10519f00-3f57-11e9-8080-cbfeafb8719c.png)

**Comment by ZarshaB** [comment]
23>> Please apply same checks for password as we have on sign up page.
![image](https://user-images.githubusercontent.com/35685146/53796976-10519f00-3f57-11e9-8080-cbfeafb8719c.png)

**Comment by ZarshaB** [comment]
24>> Change password link should get expired if user has clicked it already. And also if user has not clicked it then after 24 hours it should get expired. This message should be displayed. 
"The link you have provided has expired. Please try again to reset your password."

**Comment by sammiullah** [comment]
FIXED 19 >> There should also be dollar sign before balance and it should be two decimal places. 
![image](https://user-images.githubusercontent.com/35685146/53740889-09734f80-3eb7-11e9-8cb7-883fc6f73701.png)

**Comment by sammiullah** [comment]
**suggest the message Please**
 12) this is meaninguless 
![image](https://user-images.githubusercontent.com/10880558/53802930-fb7c0800-3f64-11e9-905f-2927b1ffafcd.png)

**Comment by ZarshaB** [comment]
12) this is meaningless:
Please add this message:
" There is a request for buying 1 DID(s) having price of  $20.00. It is pending for approval. "
" There is a request of TopUp having price of $10.00. It is pending for approval."
![image](https://user-images.githubusercontent.com/10880558/53802930-fb7c0800-3f64-11e9-905f-2927b1ffafcd.png)

**Comment by ZarshaB** [comment]
25>> On clicking on checkout it redirects me to this page.
![image](https://user-images.githubusercontent.com/35685146/53875872-5bd37e00-4027-11e9-8d31-a45e89b1a845.png)

**Comment by ZarshaB** [comment]
**Reopened**
21>> There will be four status:
Active, Waiting for Approval, Suspend, In Process.
User should be displayed with status of his account.
>>>>>>>>>>>>

Okay there are these status. But when I choose In Process then after confirmation pop up it becomes Active. 
User is not displayed with message for in which state his account is if it is in suspended or in Process state.
If I select Active then it's dots alignment disturbs.
![image](https://user-images.githubusercontent.com/35685146/53878001-896ef600-402c-11e9-882a-50aec5675fc6.png)

**Comment by ZarshaB** [comment]
25>> Please also add new added status here. As for now when I select any status then it does not appear in field.
![image](https://user-images.githubusercontent.com/35685146/53878077-bfac7580-402c-11e9-8bdc-73192663f9f2.png)

**Comment by ZarshaB** [comment]
**Still there**
18>> When I approve account then Marginal Percentage, API access etc field does not appear automatically and I have to refresh my account. Also when I approve DID then that DID does not appear in DID tab. I have to again come to the page from Reseller page.

**Comment by ZarshaB** [comment]
**Still there**
10) i was logged in, my account was still pending although it was approved by admin.
 I logged out and re login then it was showing approved.
![image](https://user-images.githubusercontent.com/35685146/53961201-d70d6080-4109-11e9-89f5-db43ad90e4e1.png)

**Comment by asifjans** [comment]
11) we need to add Payments page in seller section display payments as

if user click on any payment we will display details as

![image](https://user-images.githubusercontent.com/10880558/53967742-9583b200-4117-11e9-9a4f-b5893367d541.png)
