### ISSUE TITLE
voicesky Pending Tasks

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#17]

**Comment by ZarshaB** [comment]
1) Verify Request.

**Comment by ZarshaB** [comment]
Create a page of 2Fa Report for Reseller.

**Comment by asifjans** [comment]
UI/UX Tasks:
5) New theme Integrations for Reseller Portal
6) 	New theme Integrations for Admin Portal

**Comment by asifjans** [comment]
7) Loading icon must be some descent image
that give professional impression.
![loadingg](https://user-images.githubusercontent.com/10880558/54546393-64339d80-49c5-11e9-818f-03d364c950f8.gif)

**Comment by asifjans** [comment]
8) on Signup page i see only loading icon.........
register process not completed.
