### ISSUE TITLE
Admin New Theme Issues 9th April 2019

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#20]

**Comment by ZarshaB** [comment]
1>> This text needs to be changed. 
![image](https://user-images.githubusercontent.com/35685146/55781884-9025d880-5ac4-11e9-93b0-69120938760b.png)

**Comment by ZarshaB** [comment]
2>> No fav icon on Login page.

**Comment by ZarshaB** [comment]
3>> Site name is not visible.
![image](https://user-images.githubusercontent.com/35685146/55782094-09bdc680-5ac5-11e9-87ee-39945e7e49ad.png)

**Comment by ZarshaB** [comment]
4>> Menu does not expand.
![image](https://user-images.githubusercontent.com/35685146/55782338-7f299700-5ac5-11e9-96b2-988fa540b5c2.png)

**Comment by ZarshaB** [comment]
5>> Fav-icon is not correct.
![image](https://user-images.githubusercontent.com/35685146/55782369-8e104980-5ac5-11e9-9178-de6f77e186e4.png)

**Comment by ZarshaB** [comment]
6>> On clicking on details, it is redirecting to old theme page.
![image](https://user-images.githubusercontent.com/35685146/55782410-a84a2780-5ac5-11e9-90fc-249316cbe937.png)
![image](https://user-images.githubusercontent.com/35685146/55782419-ae400880-5ac5-11e9-8fa4-8aa47a9316fc.png)

**Comment by ZarshaB** [comment]
7>> It does not have the search bar on basis of fields that we have in old site.
![image](https://user-images.githubusercontent.com/35685146/55783382-b9943380-5ac7-11e9-99b9-00ac45bce95c.png)

**Comment by sammiullah** [comment]
**ALL issue logged here are RFR Release please Test and remove the fixed one .**

**Comment by ZarshaB** [comment]
1>> This does not seem like button but on hover button appears. And it's placement is also not correct. 
![image](https://user-images.githubusercontent.com/35685146/56046822-8e2a7680-5d5d-11e9-9e49-28078661ea68.png)

**Comment by ZarshaB** [comment]
2>> Message should be:
Are you sure you want to change the status of Reseller?
![image](https://user-images.githubusercontent.com/35685146/56047021-faa57580-5d5d-11e9-97ed-a1e236bdc3c6.png)

**Comment by ZarshaB** [comment]
3>> This success message is not correct. Please change it to:
You have changed the status of Reseller successfully.
![image](https://user-images.githubusercontent.com/35685146/56047085-190b7100-5d5e-11e9-983b-aaa9ce5932ec.png)

**Comment by ZarshaB** [comment]
4>> I think instead of highlighted message we should display following message:
Your changes have been saved successfully.
![image](https://user-images.githubusercontent.com/35685146/56047215-625bc080-5d5e-11e9-9068-f553bfd69fdd.png)

**Comment by ZarshaB** [comment]
5>> When I deactivate this then why does save icon appears? It does not appear when I activate it or do the same action for API access field.
![image](https://user-images.githubusercontent.com/35685146/56047445-d6966400-5d5e-11e9-9a45-2d30478cf018.png)

**Comment by ZarshaB** [comment]
6>> Please change this message to:
Are you sure you want to perform this action? There would be no undo.
And also change option to "Go Ahead." 
![image](https://user-images.githubusercontent.com/35685146/56047537-0c3b4d00-5d5f-11e9-82f3-33a2eebcb9a7.png)

**Comment by ZarshaB** [comment]
7>> Please remove this dot from this message pop up.
![image](https://user-images.githubusercontent.com/35685146/56047758-8ff53980-5d5f-11e9-9127-6d6f8019cbf9.png)

**Comment by ZarshaB** [comment]
8>> There are no pending payments but it is still displaying me badge icon.
![image](https://user-images.githubusercontent.com/35685146/56047897-da76b600-5d5f-11e9-9aaa-94382375aa66.png)

**Comment by ZarshaB** [comment]
9>> Opening it in new tab redirects to 404 error.
![image](https://user-images.githubusercontent.com/35685146/56048891-d77cc500-5d61-11e9-9597-edbcc261ed8b.png)

**Comment by ZarshaB** [comment]
10>> Message should be:
Changes Saved.
![image](https://user-images.githubusercontent.com/35685146/56048974-f713ed80-5d61-11e9-98da-e0b29ceee05b.png)

**Comment by ZarshaB** [comment]
11>> It is not displaying me account created on selected date.
![image](https://user-images.githubusercontent.com/35685146/56049057-1f035100-5d62-11e9-8fe3-006d5d127c17.png)

**Comment by ZarshaB** [comment]
11>> Please change this option to "Sure" as we are using this for other pop up too.
![image](https://user-images.githubusercontent.com/35685146/56049417-dd26da80-5d62-11e9-84a1-5d49e09f71d0.png)

**Comment by ZarshaB** [comment]
1>> Please add currency sign with price.
![image](https://user-images.githubusercontent.com/35685146/56122487-f068be80-5f8b-11e9-8229-8ab120ad20a3.png)

**Comment by ZarshaB** [comment]
2>> When I cancel any payment then it's alignment disturbs.
![image](https://user-images.githubusercontent.com/35685146/56122569-24dc7a80-5f8c-11e9-91f9-4566184f1e30.png)

**Comment by ZarshaB** [comment]
3>> Please add dollar sign and make it to two decimal places.
![image](https://user-images.githubusercontent.com/35685146/56122716-7553d800-5f8c-11e9-85ea-bd72b5195c1c.png)

**Comment by ZarshaB** [comment]
4>> Please add dollar signs.
![image](https://user-images.githubusercontent.com/35685146/56122869-d085ca80-5f8c-11e9-8293-2888ae2745ed.png)

**Comment by sammiullah** [comment]
Please test all the above issues
