### ISSUE TITLE
UI - Register

### ISSUE THREAD

**Issue by asifjans** [asifjans/voicesky#3]
**FIXED**
![image](https://user-images.githubusercontent.com/10880558/46153369-70e3fe00-c28c-11e8-975d-6a1fe2ef6c7c.png)

![image](https://user-images.githubusercontent.com/10880558/46153392-7e998380-c28c-11e8-8cfe-7c36b88b7bfd.png)

![image](https://user-images.githubusercontent.com/10880558/46153517-bacce400-c28c-11e8-88ff-b642c6fc2063.png)

![image](https://user-images.githubusercontent.com/10880558/46153695-16976d00-c28d-11e8-9fff-56bd2da8b68f.png)

**Comment by sammiullah** [comment]
**Sign Up** 
1.By default UK should be selected in country list.
2.Spaces b/w Fields

**Footer**
3.Set Map to Address to UK address of Inovedia

**Admin**
4.Delete Reseller button at the start of list. (after first click POP up should be there, That all the data of this reseller will be deleted from all tables).
5.In Payment table change button "ACTIVE" to "Approve".

**Notification**
6.There will be a notification icon in header with number of notifications, on hover it will show drop down of  all notifications and at the end of there will be a VIEW ALL button.

**View ALL notifications**
7.There will be a delete button at the end of each notification and check box at the start of each notification, Reseller can select many notifications and delete them. (Delete Selected button will be at the button)

**Dashboard**
8.Dashboard menu icons must be different.
9. TRY API, make text colorful.

**Sign Up**
10.Sign Up Button Issue not working.

**Email Templates**
Brackets are appearing around the Email of info@.....
