### ISSUE TITLE
UI 22-11-2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#6]

**Comment by ZarshaB** [comment]
1>> Buttons are overlapping.
![image](https://user-images.githubusercontent.com/35685146/48895905-0e604600-ee68-11e8-8f9e-3f02fb4cdd4a.png)

**Comment by ZarshaB** [comment]
2>> Sir says that these error messages should be with the fields instead of displaying at top.
![image](https://user-images.githubusercontent.com/35685146/48895959-3a7bc700-ee68-11e8-97cf-9b884f054dd5.png)

**Comment by ZarshaB** [comment]
3>> It should be Congratulations as Congo looks unprofessional.
![image](https://user-images.githubusercontent.com/35685146/48896013-5f703a00-ee68-11e8-8cda-63f15686759a.png)

**Comment by ZarshaB** [comment]
3>> Grammatical error. It should be:
Ooops.. Old password does not match.
![image](https://user-images.githubusercontent.com/35685146/48896064-8595da00-ee68-11e8-929f-0c5b834b6aa9.png)

**Comment by ZarshaB** [comment]
4>> Messages should be disappeared after some time. As I have changed password and then again when I changed password it showed be both success and error messages.
![image](https://user-images.githubusercontent.com/35685146/48896138-b4ac4b80-ee68-11e8-90c5-77c842ea4009.png)

**Comment by ZarshaB** [comment]
5>> Please put full stop after every message.
![image](https://user-images.githubusercontent.com/35685146/48896200-d6a5ce00-ee68-11e8-9629-c205bd9ae17f.png)

**Comment by ZarshaB** [comment]
6>> I think it would be better if we write:
Didn't get the email? Please check your spam folder.
![image](https://user-images.githubusercontent.com/35685146/48896261-fdfc9b00-ee68-11e8-9524-efc4abf389ea.png)

**Comment by ZarshaB** [comment]
7>> It is overlapping.
![image](https://user-images.githubusercontent.com/35685146/48896331-32705700-ee69-11e8-9c49-50807bcf458f.png)

**Comment by ZarshaB** [comment]
8>> Voicesky Admin page:
If credentials are saved then it overlaps with placeholder.
![image](https://user-images.githubusercontent.com/35685146/48897171-30a79300-ee6b-11e8-9dec-5207b8c9a911.png)

**Comment by ZarshaB** [comment]
9>> This dashboard of Admin is not appealing.
![image](https://user-images.githubusercontent.com/35685146/48897423-e2df5a80-ee6b-11e8-8e6d-f2f47dda8cea.png)

**Comment by ZarshaB** [comment]
10>> Please change it to:
Email is already registered.
![image](https://user-images.githubusercontent.com/35685146/48899832-7e73c980-ee72-11e8-91ae-261687b36481.png)

**Comment by ZarshaB** [comment]
15>> Please this message to:
Ahhhh!!! A password confirmation mismatch. Please try again.
![image](https://user-images.githubusercontent.com/35685146/48906539-a10fdd80-ee86-11e8-9841-b6c42352a298.png)

**Comment by sammiullah** [comment]
**All above issues are fixed and ready for testing.**

**Comment by ZarshaB** [comment]
11>> Re-opened:
Message has been changed now but when I click on submit button after entering password then it displayed error page.
![image](https://user-images.githubusercontent.com/35685146/49008927-eedf5b00-f190-11e8-8ea9-63bf2c346e8e.png)

**Comment by ZarshaB** [comment]
10,13,15 >> Not Fixed.

**Comment by sammiullah** [comment]
11>> Re-opened: **FIXED**
Message has been changed now but when I click on submit button after entering password then it displayed error page.
![image](https://user-images.githubusercontent.com/35685146/49008927-eedf5b00-f190-11e8-8ea9-63bf2c346e8e.png)
