### ISSUE TITLE
Site Issues 27-11-2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#8]

**Comment by ZarshaB** [comment]
1>> Profile Photo option should be at the top I think.
![image](https://user-images.githubusercontent.com/35685146/49089255-efedb680-f27c-11e8-9971-13fc2d88fcc8.png)

**Comment by ZarshaB** [comment]
2>> Please put full stop at the end of sentence.
![image](https://user-images.githubusercontent.com/35685146/49090196-0c8aee00-f27f-11e8-9a9b-d554362d6351.png)

**Comment by ZarshaB** [comment]
3>> Please remove this search option as it is not required.
![image](https://user-images.githubusercontent.com/35685146/49090460-963abb80-f27f-11e8-8bad-865267009ea6.png)

**Comment by ZarshaB** [comment]
4>> Secret spelling is not correct.
![image](https://user-images.githubusercontent.com/35685146/49090517-b7031100-f27f-11e8-8d75-e0e7adc872f2.png)

**Comment by ZarshaB** [comment]
5>> T of Thursday should be in capital like all other words.
![image](https://user-images.githubusercontent.com/35685146/49090807-4b6d7380-f280-11e8-8301-282196d68291.png)

**Comment by ZarshaB** [comment]
6>> Please put space between place holder of First Name and Last Name.
![image](https://user-images.githubusercontent.com/35685146/49090888-7a83e500-f280-11e8-8d4d-9fdb6376a02f.png)

**Comment by ZarshaB** [comment]
7>> Should not it be the name of image instead of displaying "No File Chosen"?
![image](https://user-images.githubusercontent.com/35685146/49090959-a737fc80-f280-11e8-835e-fb55981932a7.png)

**Comment by ZarshaB** [comment]
8>> Please add here this text in empty cart.
![image](https://user-images.githubusercontent.com/35685146/49091089-f2520f80-f280-11e8-8d2c-1305d42b0d0f.png)
![image](https://user-images.githubusercontent.com/35685146/49091108-f9791d80-f280-11e8-9199-57098d7ce3d2.png)

**Comment by ZarshaB** [comment]
9>> If now I click on cart option then it should display me message to add quantity.
![image](https://user-images.githubusercontent.com/35685146/49091223-2decd980-f281-11e8-910b-b0a3221a54b3.png)

**Comment by ZarshaB** [comment]
10>> Show entries should be in one line. As it does not look okay like this.
![image](https://user-images.githubusercontent.com/35685146/49091313-583e9700-f281-11e8-9c00-d35e7a5cbdde.png)

**Comment by ZarshaB** [comment]
11>> Please change the color of warning to yellow.
![image](https://user-images.githubusercontent.com/35685146/49091384-9045da00-f281-11e8-8af3-76e3196c0dd5.png)

**Comment by ZarshaB** [comment]
12>> Google map is not working.
![image](https://user-images.githubusercontent.com/35685146/49091460-bc615b00-f281-11e8-8214-9954c7356f71.png)

**Comment by ZarshaB** [comment]
13>> There is much space.
![image](https://user-images.githubusercontent.com/35685146/49093268-8cb45200-f285-11e8-8b02-90b2741447cd.png)

**Comment by ZarshaB** [comment]
14>> Heading should have bolder font than other text.
![image](https://user-images.githubusercontent.com/35685146/46137783-c3f58b00-c263-11e8-8a55-76df31cc352d.png)

**Comment by ZarshaB** [comment]
15) Image size changes as I expand question.
![image](https://user-images.githubusercontent.com/35685146/46137912-0dde7100-c264-11e8-8af6-4d3e5f3c43c6.png)
![image](https://user-images.githubusercontent.com/35685146/46137931-16cf4280-c264-11e8-93d6-b54b18df8f71.png)

**Comment by ZarshaB** [comment]
16>> If I expand any one of these two last questions then it expand the other one too.
![image](https://user-images.githubusercontent.com/35685146/46137998-336b7a80-c264-11e8-964e-2d7d050cdd5b.png)

**Comment by ZarshaB** [comment]
17>> Heading should be in middle of two blocks.
![image](https://user-images.githubusercontent.com/35685146/46138181-ac6ad200-c264-11e8-8ab1-17abca371c4c.png)

**Comment by ZarshaB** [comment]
18>> The font of text should be white so that it could be visible. 
![image](https://user-images.githubusercontent.com/35685146/49141036-82db2f00-f317-11e8-9741-44d52ac0b8b3.png)

**Comment by ZarshaB** [comment]
19>> We can change it's text with this one:
![image](https://user-images.githubusercontent.com/35685146/49142530-cc794900-f31a-11e8-90cb-36369ec1cd83.png)
![image](https://user-images.githubusercontent.com/35685146/49142548-d8650b00-f31a-11e8-92b7-ac9f1a314381.png)

**Comment by sammiullah** [comment]
**Following issues are Fixed** please test.
1,2,3,4,5,6,7,8,9,14,15,16,18,19

**Comment by sammiullah** [comment]
**Following issues are Fixed** please test.
1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,18,19 

**12 and 17 are Pending issues**

**Comment by ZarshaB** [comment]
**Re-opened**
4>> It's spelling is now correct but first letter has made small now. Please keep it capital.
![image](https://user-images.githubusercontent.com/35685146/49294223-2ec97980-f4d4-11e8-9e46-baceede22873.png)

**Comment by ZarshaB** [comment]
**Re-opened**
8>> Okay text is changed. But can you make it center aligned? 
![image](https://user-images.githubusercontent.com/35685146/49294547-1574fd00-f4d5-11e8-81e5-9adedfe2e68b.png)

**Comment by ZarshaB** [comment]
11>> Please change it's color to red.
