### ISSUE TITLE
Voicesky Content

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#9]

**Comment by sammiullah** [comment]
SIP Truncking.

Make Cost effective communication with Adaptable SIP Truncking.

In this modern world of technology, there can be many acronyms for keeping track.
But right now what your business needs most is SIP trunking. 
And here comes Voicesky to help you in making things smooth for you.

Voicesky untangle and simplify communications and help you to connect with the world in minutes.
Are you still waiting for extreme traffic? No more wait.
Let's save costs with per-second billing feature. Which means you will only pay for what you utilized and no extra charges. Interesting hah?
In addition to this you can now easily communicate globally.
